### ISSUE TITLE
Fragment to handle respones

### ISSUE THREAD

**Issue by mamayoleksandr** [JacpFX/JacpFX#30]
So currently a Fragment can send messages to components and callbacks, using context. How it would handle response from such calls? Would it work if fragment implements FXComponent?

**Comment by mamayoleksandr** [comment]
Hi Andy,

if message is sent from a Fragment to to a Callback (assuming response should be sent to caller by default), I got such exception:
INFO: org.jacpfx.api.exceptions.ComponentNotFoundException: no perspective for message : wMain.pMain found
	at org.jacpfx.rcp.delegator.MessageDelegatorImpl.handleCall(MessageDelegatorImpl.java:60)
	at org.jacpfx.rcp.delegator.MessageDelegatorImpl.run(MessageDelegatorImpl.java:43)

But if I manually define response component/perspective by means of context.setReturnTarget(idcmp); then all fine.

thanks,

Alex.

**Comment by amoAHCP** [comment]
Hi, I have created a Test with Dialogs and CallbackComponents and it works as expected?! The Dialog is child of a FXComponent, inside the Dialog I send a message to a CallbackComponent (inside the same perspective AND to an other Perspective)... in both cases the CallbackComponent sends the return message back to the FXComponent, which is the parent of the Dialog. A Dialog can't be a message target itself... it is a kind of "lightweight" component. Can you provide a small testcase? THX Andy
