### ISSUE TITLE
NoSuchFieldException in AFXWorkbench

### ISSUE THREAD

**Issue by mg-2014** [JacpFX/JacpFX#53]
`NoSuchFieldException` when calling `AFXWorkbench.unregisterComponent()` since there is no field `messageQueue` in AFXPerspective. The exception is not propagated but logged only:
```
ERROR] null
java.lang.NoSuchFieldException: messageQueue
	at java.lang.Class.getDeclaredField(Class.java:2070) ~[?:1.8.0_101]
	at org.jacpfx.rcp.util.FXUtil.setPrivateMemberValue(FXUtil.java:127) ~[classes/:?]
	at org.jacpfx.rcp.workbench.AFXWorkbench.unregisterComponent(AFXWorkbench.java:292) ~[classes/:?]
[...]
```
I don't know if this is still relevant since the entire method is annotated by "remove this" in version 2.1.

(Issue is related to version 2.1.)

**Comment by amoAHCP** [comment]
fixed in https://github.com/JacpFX/JacpFX/commit/49ba3ed1e9cf8cdef5e19ac0afced60bbc734b30
