### ISSUE TITLE
Packaging executable jar file: jar file cannot start like debug using intelliJ IDE

### ISSUE THREAD

**Issue by huynhthanhbinh** [JacpFX/JacpFX#72]
I am trying to make a JavaFX application using JACP FX, Maven, SpringBoot, MapStruct, Lombok.
All thing works normally as I use IntelliJ IDE to debug. App runs normally, from start to close !

But when I decide to package it as a jar (using spring-boot-maven-plugin), the jar cannot start !
An exception was thrown:  **ComponentNotFoundException**, I see it cannot find the perspective !

- My workbench:
https://github.com/huynhthanhbinh/PIM/blob/57e184b7a5735f57ebe86adfceb14b69bbc7181d/CLIENT/src/main/java/com/bht/pim/AppWorkbench.java

- My perspectives:
https://github.com/huynhthanhbinh/PIM/tree/57e184b7a5735f57ebe86adfceb14b69bbc7181d/CLIENT/src/main/java/com/bht/pim/perspective

- Project folder:
https://github.com/huynhthanhbinh/PIM/tree/57e184b7a5735f57ebe86adfceb14b69bbc7181d/CLIENT/src/main/java/com/bht/pim

- Exception:
Caused by: org.jacpfx.api.exceptions.ComponentNotFoundException: following perspective or component id was not found: pimPerspective

	at org.jacpfx.rcp.registry.ClassRegistry.checkAndGetClassSearch(ClassRegistry.java:114)
	at org.jacpfx.rcp.registry.ClassRegistry.getPerspectiveClassById(ClassRegistry.java:109)
	at org.jacpfx.rcp.util.WorkbenchUtil.mapToInjectable(WorkbenchUtil.java:158)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at org.jacpfx.rcp.util.WorkbenchUtil.createPerspectiveInstances(WorkbenchUtil.java:86)
	at org.jacpfx.rcp.workbench.AFXWorkbench.start(AFXWorkbench.java:108)
	at org.jacpfx.rcp.workbench.AFXWorkbench.init(AFXWorkbench.java:165)
	...............................

Can you provide me any solution ? Thanks for support !

**Comment by SMONTA** [comment]
I encountered same issue as you. I'm using spring boot 2.6.6 , java 17, javafx 17 and jacpFx lib. 
I seems that the issue comes from maven plugin 
`<plugin>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-maven-plugin</artifactId>
      </plugin>`

I found a workaround to create the jar file using an other maven plugin. 
I used maven-assembly-plugin instead of spring-boot-maven-plugin:  
Here after the config: 
` <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-assembly-plugin</artifactId>
        <version>3.3.0</version>
        <configuration>
          <archive>
            <manifest>
              
              <mainClass><Path to Main Class></mainClass>
            </manifest>
          </archive>
          <descriptorRefs>
            
            <descriptorRef>jar-with-dependencies</descriptorRef>
          </descriptorRefs>
          <appendAssemblyId>false</appendAssemblyId>
        </configuration>
        <executions>
          <execution>
            <id>make-assembly</id>
            <phase>package</phase>
            <goals>
              <goal>single</goal>
            </goals>
          </execution>
        </executions>
      </plugin>`

It is too late but it can be useful for some else.
